server:
  port: 3344
spring:
  application:
    name: cloud-config-center # 注册进Eureka服务器的微服务名
  cloud:
    config:
      server:
        git:
          uri: https://github.com/geyiwei-suzhou/springcloud-config.git # 私库需要配置ssh秘钥或者配置用户名、密码
          # 搜索目录
          search-paths:
            - springcloud-config
          # 读取分支
          default-label: master
  # rabbitmq相关配置
  rabbitmq:
    host: localhost
    port: 5672
    usrname: guest
    password: guest

# 暴露bus刷新配置的端点
management:
  endpoints: # 暴露bus刷新配置的端点
    web:
      exposure:
        include: 'bus-refresh'

# 服务注册到eureka地址
eureka:
  client:
    service-url:
      defaultZone: http://localhost:7001/eureka
