server:
  port: 7001
eureka:
  instance:
    hostname: eureka7001.com #eureka服务端的实例名称
  client:
    register-with-eureka: false #false表示不向注册中心注册自己
    fetch-registry: false #false表示自己就是注册中心，职责就是维护服务实例，不需要检索服务
    service-url:
      #单机版
      defaultZone: http://eureka7001.com:7001/eureka/
      #集群版
      #defaultZone: http://eureka7002.com:7002/eureka/ #设置与Eureka Server交互的地址查询服务和注册服务都需要依赖这个地址, 3台及以上集群，多个defaultZone使用逗号隔开
  server:
    enable-self-preservation: false #默认为true, 关闭自我保护机制，保证不可用服务被及时剔除
    eviction-interval-timer-in-ms: 2000